/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
        RouteRecordInfo
    } from 'vue-router';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AddProduct': RouteRecordInfo<'/AddProduct', '/AddProduct', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Invoices': RouteRecordInfo<'/Invoices', '/Invoices', Record<never, never>, Record<never, never>>,
    '/Orders': RouteRecordInfo<'/Orders', '/Orders', Record<never, never>, Record<never, never>>,
    '/Picking': RouteRecordInfo<'/Picking', '/Picking', Record<never, never>, Record<never, never>>,
    '/Products': RouteRecordInfo<'/Products', '/Products', Record<never, never>, Record<never, never>>,
    '/Shipping': RouteRecordInfo<'/Shipping', '/Shipping', Record<never, never>, Record<never, never>>,
    '/add-product': RouteRecordInfo<'/add-product', '/add-product', Record<never, never>, Record<never, never>>,
  }
}
